# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# frozen_string_literal: true

# stub: engaging-networks-rest 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = 'engaging-networks-rest'
  s.version = '0.6.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['Jacinda Moore']
  s.date = '2021-03-23'
  s.description = 'Client gem for the ENS API to Engaging Networks'
  s.email = 'jacinda@controlshiftlabs.com'
  s.extra_rdoc_files = [
    'LICENSE',
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.ruby-gemset',
    '.ruby-version',
    'Gemfile',
    'LICENSE',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'engaging-networks-rest.gemspec',
    'example.rb',
    'lib/engaging_networks_rest.rb',
    'lib/engaging_networks_rest/client.rb',
    'lib/engaging_networks_rest/client/pages.rb',
    'lib/engaging_networks_rest/response/raise_error.rb',
    'spec/client/pages_spec.rb',
    'spec/client_spec.rb',
    'spec/spec_helper.rb'
  ]
  s.homepage = 'http://github.com/controlshift/engaging-networks-rest'
  s.licenses = ['MIT']
  s.rubygems_version = '3.0.8'
  s.summary = 'Client gem for the ENS API to Engaging Networks'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('faraday', ['>= 1.0'])
      s.add_runtime_dependency('faraday_middleware', ['>= 0'])
      s.add_development_dependency('faker', ['> 1.9'])
      s.add_development_dependency('faraday-detailed_logger', ['>= 2.1.2'])
      s.add_development_dependency('juwelier', ['>= 0'])
      s.add_development_dependency('pry-byebug', ['> 3.6'])
      s.add_development_dependency('rspec', ['>= 0'])
      s.add_development_dependency('webmock', ['> 3.4'])
    else
      s.add_dependency('faker', ['> 1.9'])
      s.add_dependency('faraday', ['>= 1.0'])
      s.add_dependency('faraday-detailed_logger', ['>= 2.1.2'])
      s.add_dependency('faraday_middleware', ['>= 0'])
      s.add_dependency('juwelier', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('webmock', ['> 3.4'])
    end
  else
    s.add_dependency('faraday', ['>= 1.0'])
    s.add_dependency('faraday_middleware', ['>= 0'])
    s.add_dependency('pry-byebug', ['> 3.6'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('webmock', ['> 3.4'])
    s.add_dependency('webmock', ['> 3.4'])
    s.add_dependency('webmock', ['> 3.4'])
  end
end
