name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1, 3.2]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1, 3.2]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rubocop
